# Generated by Django 4.2.20 on 2025-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('OOP', 'Object-Oriented Programming'), ('SE', 'Software Engineering')], max_length=3)),
                ('resource', models.URLField(max_length=2000)),
                ('study_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=12)),
            ],
        ),
    ]
