# Generated by Django 4.2.20 on 2025-04-25 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('Study', 'Study'), ('Review', 'Review'), ('Project', 'Project'), ('Exam', 'Exam')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('estimated_study_hours', models.FloatField()),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
