# Generated by Django 4.2.20 on 2025-04-25 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_taskevent_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_strengths', models.JSONField(default=list)),
                ('selected_weaknesses', models.JSONField(default=list)),
                ('hours_per_day', models.IntegerField(default=2)),
                ('days_per_week', models.IntegerField(default=5)),
                ('preferred_study_time', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Night', 'Night'), ('Any time', 'Any time')], default='Morning', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
