# Generated by Django 4.2.20 on 2025-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='selected_strengths',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='selected_weaknesses',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='strengths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weaknesses',
            field=models.JSONField(default=list),
        ),
    ]
