# Generated by Django 4.2.20 on 2025-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='task_name',
            field=models.CharField(default='Default Task Name', max_length=100),
            preserve_default=False,
        ),
    ]
