# Generated by Django 4.2.20 on 2025-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_taskevent_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
