# Generated by Django 4.2.20 on 2025-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_taskevent_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Complete', 'Not Complete'), ('Complete', 'Complete'), ('Deleted', 'Deleted')], default='Pending', max_length=20),
        ),
    ]
