# Generated by Django 4.2.20 on 2025-04-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_studyplan_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='event_id',
        ),
    ]
