# Generated by Django 4.2.20 on 2025-04-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_studyplan_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.taskevent'),
            preserve_default=False,
        ),
    ]
