# Generated by Django 4.2.20 on 2025-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_studyplan_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='skip_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
