# Generated by Django 4.2.20 on 2025-04-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_taskevent_skip_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='hours_per_day',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_study_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Night', 'Night')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
